"""Generate LLaMA-Factory dataset registration, training YAML, and the
sbatch script for a fine-tuning job, from the wizard's collected answers."""

import json
import os
import textwrap

from . import cluster_policy


def dataset_info_entry(fmt: str) -> dict:
    if fmt == "alpaca":
        return {"file_name": "dataset.json"}
    if fmt == "sharegpt":
        return {
            "file_name": "dataset.json",
            "formatting": "sharegpt",
            "columns": {"messages": "conversations"},
            "tags": {
                "role_tag": "from",
                "content_tag": "value",
                "user_tag": "human",
                "assistant_tag": "gpt",
            },
        }
    if fmt == "sharegpt_messages":
        return {
            "file_name": "dataset.json",
            "formatting": "sharegpt",
            "columns": {"messages": "messages"},
            "tags": {
                "role_tag": "role",
                "content_tag": "content",
                "user_tag": "user",
                "assistant_tag": "assistant",
            },
        }
    raise ValueError(f"Unknown dataset format: {fmt}")


def write_dataset_registration(job_dir: str, dataset_src_path: str, fmt: str, ext: str):
    data_dir = os.path.join(job_dir, "data")
    os.makedirs(data_dir, exist_ok=True)
    dst = os.path.join(data_dir, "dataset.json")
    # Symlink rather than copy: datasets can be large and users may keep
    # editing them; a symlink keeps the job pointed at the live file.
    if os.path.islink(dst) or os.path.exists(dst):
        os.remove(dst)
    os.symlink(os.path.abspath(dataset_src_path), dst)

    info = {"dataset": dataset_info_entry(fmt)}
    with open(os.path.join(data_dir, "dataset_info.json"), "w", encoding="utf-8") as f:
        json.dump(info, f, indent=2)
    return data_dir


def write_train_config(
    job_dir: str,
    data_dir: str,
    model: dict,
    method: dict,
    gpus: int,
    epochs: float,
    learning_rate: float,
    batch_size: int,
    cutoff_len: int,
    hf_home: str,
) -> str:
    output_dir = os.path.join(job_dir, "output")
    os.makedirs(output_dir, exist_ok=True)

    lines = [
        f"# Auto-generated by the NANO4 fine-tuning wizard.",
        f"model_name_or_path: {model['repo_id']}",
        "trust_remote_code: true",
        "",
        "### method",
        "stage: sft",
        "do_train: true",
        f"finetuning_type: {method['finetuning_type']}",
    ]
    if method["finetuning_type"] == "lora":
        lines += ["lora_rank: 8", "lora_target: all"]
    if method.get("quantization_bit"):
        lines += [f"quantization_bit: {method['quantization_bit']}", "quantization_method: bitsandbytes"]

    lines += [
        "",
        "### dataset",
        "dataset: dataset",
        f"dataset_dir: {data_dir}",
        f"template: {model['template']}",
        f"cutoff_len: {cutoff_len}",
        "overwrite_cache: true",
        "preprocessing_num_workers: 4",
        "",
        "### output",
        f"output_dir: {output_dir}",
        "logging_steps: 5",
        "save_steps: 200",
        "plot_loss: true",
        "overwrite_output_dir: true",
        "",
        "### train",
        f"per_device_train_batch_size: {batch_size}",
        "gradient_accumulation_steps: 4",
        f"learning_rate: {learning_rate}",
        f"num_train_epochs: {epochs}",
        "lr_scheduler_type: cosine",
        "warmup_ratio: 0.1",
        "bf16: true",
    ]
    if gpus > 1:
        lines += ["", "### multi-gpu (single node)", "ddp_timeout: 180000"]

    config_path = os.path.join(job_dir, "train_config.yaml")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return config_path, output_dir


def write_sbatch_script(
    job_dir: str,
    job_name: str,
    account: str,
    partition: str,
    gpus: int,
    cpus_per_task: int,
    mem_gb: int,
    time_limit: str,
    venv_python: str,
    train_config_path: str,
    hf_home: str,
) -> str:
    logs_dir = os.path.join(job_dir, "logs")
    os.makedirs(logs_dir, exist_ok=True)

    venv_bin = os.path.dirname(venv_python)
    cli = os.path.join(venv_bin, "llamafactory-cli")
    multi_gpu_env = f"FORCE_TORCHRUN=1 NPROC_PER_NODE={gpus} " if gpus > 1 else ""
    launcher = f'{multi_gpu_env}"{cli}" train "{train_config_path}"'

    script = textwrap.dedent(f"""\
        #!/bin/bash
        #SBATCH --job-name={job_name}
        #SBATCH --account={account}
        #SBATCH --partition={partition}
        #SBATCH --gpus-per-node={gpus}
        #SBATCH --cpus-per-task={cpus_per_task}
        #SBATCH --mem={mem_gb}G
        #SBATCH --time={time_limit}
        #SBATCH --output={logs_dir}/%x-%j.out
        #SBATCH --error={logs_dir}/%x-%j.err

        set -euo pipefail

        export HF_HOME="{hf_home}"

        echo "Node: $(hostname)"
        nvidia-smi --query-gpu=name,memory.total --format=csv

        {launcher}
        """)

    path = os.path.join(job_dir, "submit.sbatch")
    with open(path, "w", encoding="utf-8") as f:
        f.write(script)
    os.chmod(path, 0o755)
    return path
